import type { ProblemBankCopy } from '@/lib/math/problems';
import { DEFAULT_AI_MODEL } from '@/lib/math/problems';

export const DEFAULT_AI_COPY = {
  title: 'ამოცანების ბანკი',
  prompt: 'პირობა',
  solution: 'ამოხსნა',
  difficulties: { easy: 'მარტივი', medium: 'საშუალო', hard: 'რთული' },
  topics: {
    algebra: 'ალგებრა',
    geometry: 'გეომეტრია',
    trigonometry: 'ტრიგონომეტრია',
    calculus: 'მათემატიკური ანალიზი',
    combinatorics: 'კომბინატორიკა',
    probability: 'ალბათობა',
    number_theory: 'რიცხვთა თეორია',
    logic: 'ლოგიკა',
    other: 'სხვა',
  },
  years: {
    grade7: 'VII კლასი',
    grade8: 'VIII კლასი',
    grade9: 'IX კლასი',
    grade10: 'X კლასი',
    grade11: 'XI კლასი',
    grade12: 'XII კლასი',
    ent: 'ეროვნული გამოცდები',
    other: 'სხვა',
  },
  chat: {
    title: 'AI ასისტენტი',
    open: 'AI ასისტენტის გახსნა',
    close: 'დახურვა',
    launcher: 'AI',
    model: 'მოდელი',
    models: {
      'gemini-flash-lite': 'Gemini 2.5 Flash Lite',
      'gemini-flash': 'Gemini 2.5 Flash',
      'gemini-pro': 'Gemini 2.5 Pro',
      'deepseek-chat': 'DeepSeek V3',
      'deepseek-reasoner': 'DeepSeek R1',
      'gpt-4o-mini': 'GPT-4o mini',
      'gpt-4o': 'GPT-4o',
      'claude-haiku': 'Claude 3.5 Haiku',
      'claude-sonnet': 'Claude 3.7 Sonnet',
    },
    limitLabel: 'ლიმიტი',
    limitNoKey: 'გასაღები არაა მითითებული',
    limitExhausted: 'ლიმიტი ამოიწურა',
    limitReady: 'მზადაა',
    limitUsed: 'გამოყენებულია: {used}/{limit}',
    replyLanguage: 'პასუხის ენა',
    languages: {
      ka: 'ქართული',
      en: 'English',
    },
    clear: 'გასუფთავება',
    emptyTitle: 'დასვით კითხვა, ჩასვით (Ctrl+V) სურათი ან მოითხოვეთ ამოცანა',
    you: 'თქვენ',
    assistant: 'ასისტენტი',
    cardsTitle: 'ამოცანის ბარათები',
    savingCard: 'ინახება...',
    saveToBank: 'ბანკში შენახვა',
    saveAllToBank: 'ყველას ბანკში შენახვა',
    saveToLab: 'ლაბორატორიაში შენახვა',
    saveAllToLab: 'ყველას ლაბორატორიაში შენახვა',
    savedToBank: 'შენახულია ბანკში',
    savedToLab: 'შენახულია ლაბორატორიაში',
    saveFailed: 'შენახვა ვერ მოხერხდა',
    addImage: 'სურათის დამატება',
    imageHint: 'შეგიძლიათ ატვირთოთ ან ჩასვათ (Ctrl+V) ამოცანის სურათი',
    removeImage: 'სურათის წაშლა',
    inputLabel: 'ტექსტი',
    inputPlaceholder: 'ჩაწერეთ შეკითხვა, მათემატიკური ამოცანა ან ჩასვით სურათი...',
    previewLabel: 'KaTeX წინასწარი ნახვა',
    sending: 'იგზავნება...',
    send: 'გაგზავნა',
    thinking: 'AI ფიქრობს...',
    emptyReply: 'პასუხი ცარიელია',
    errorMissingKey: 'API გასაღები არ არის მითითებული',
    errorInvalidKey: 'API გასაღები არასწორია',
    errorLimit: 'მოთხოვნების ლიმიტი ამოიწურა',
    errorBilling: 'ბილინგის შეცდომა',
    errorTimeout: 'მოთხოვნის დრო ამოიწურა',
    errorUnauthorized: 'ავტორიზაციის შეცდომა',
    errorBadOutput: 'არასწორი პასუხი',
    errorImageUnsupported: 'ეს მოდელი არ უჭერს მხარს სურათებს',
    errorFailed: 'მოთხოვნა ვერ შესრულდა',
    slashPrompts: {
      title: 'სწრაფი პრომპტები',
      manage: 'პრომპტების მართვა',
      add: 'დამატება',
      edit: 'რედაქტირება',
      delete: 'წაშლა',
      name: 'სახელი',
      prompt: 'პრომპტი',
      save: 'შენახვა',
      cancel: 'გაუქმება',
      fillTitle: 'პარამეტრების შევსება',
      fillConfirm: 'ჩასმა',
      noPrompts: 'პრომპტები არ არის',
    },
  },
} as unknown as ProblemBankCopy;

export { DEFAULT_AI_MODEL };
