import type { BankProblem } from "./types";

/** Curated starter bank. Replace with Prisma rows when the LMS schema lands. */
export const SEED_PROBLEM_BANK: BankProblem[] = [
  {
    id: "bank-lin-01",
    templateId: "linear-two-step",
    topic: "algebra",
    difficulty: "easy",
    year: "7",
    source: "bank",
    instructionId: "solve",
    promptTex: "2x + 5 = 17",
    solutionTex: "x = 6",
  },
  {
    id: "bank-lin-02",
    templateId: "linear-both-sides",
    topic: "algebra",
    difficulty: "medium",
    year: "8",
    source: "bank",
    instructionId: "solve",
    promptTex: "5x - 3 = 2x + 9",
    solutionTex: "x = 4",
  },
  {
    id: "bank-quad-01",
    templateId: "quadratic-monic",
    topic: "equations",
    difficulty: "medium",
    year: "9",
    source: "bank",
    instructionId: "solve",
    promptTex: "x^2 - 5x + 6 = 0",
    solutionTex: "x = 2,\\; x = 3",
    graphExpr: "x^2 - 5x + 6",
  },
  {
    id: "bank-quad-02",
    templateId: "quadratic-scaled",
    topic: "equations",
    difficulty: "hard",
    year: "10",
    source: "bank",
    instructionId: "solve",
    promptTex: "2x^2 - 7x - 4 = 0",
    solutionTex: "x = 4,\\; x = -\\tfrac{1}{2}",
    graphExpr: "2x^2 - 7x - 4",
  },
  {
    id: "bank-geo-01",
    templateId: "pythagoras-hyp",
    topic: "geometry",
    difficulty: "easy",
    year: "8",
    source: "bank",
    instructionId: "missingSide",
    promptTex: "a = 6,\\; b = 8,\\; c = ?",
    solutionTex: "c = 10",
  },
  {
    id: "bank-geo-02",
    templateId: "pythagoras-leg",
    topic: "geometry",
    difficulty: "medium",
    year: "9",
    source: "bank",
    instructionId: "missingSide",
    promptTex: "a = 5,\\; c = 13,\\; b = ?",
    solutionTex: "b = 12",
  },
  {
    id: "bank-fn-01",
    templateId: "function-linear",
    topic: "functions",
    difficulty: "easy",
    year: "8",
    source: "bank",
    instructionId: "evaluate",
    promptTex: "f(x) = 3x - 4,\\; f(5) = ?",
    solutionTex: "f(5) = 11",
    graphExpr: "3x - 4",
  },
  {
    id: "bank-fn-02",
    templateId: "function-quadratic",
    topic: "functions",
    difficulty: "medium",
    year: "10",
    source: "bank",
    instructionId: "evaluate",
    promptTex: "f(x) = x^2 - 2x - 3,\\; f(4) = ?",
    solutionTex: "f(4) = 5",
    graphExpr: "x^2 - 2x - 3",
  },
  {
    id: "bank-pct-01",
    templateId: "percent-of",
    topic: "percent",
    difficulty: "easy",
    year: "7",
    source: "bank",
    instructionId: "percentOf",
    promptTex: "25\\% \\cdot 80",
    solutionTex: "20",
  },
  {
    id: "bank-pct-02",
    templateId: "percent-increase",
    topic: "percent",
    difficulty: "medium",
    year: "8",
    source: "bank",
    instructionId: "evaluate",
    promptTex: "120 + 15\\%",
    solutionTex: "138",
  },
  {
    id: "bank-cal-01",
    templateId: "derivative-quadratic",
    topic: "calculus",
    difficulty: "medium",
    year: "11",
    source: "bank",
    instructionId: "findDerivative",
    promptTex: "f(x) = 3x^2 - 4x + 1",
    solutionTex: "f'(x) = 6x - 4",
    graphExpr: "3x^2 - 4x + 1",
  },
  {
    id: "bank-cal-02",
    templateId: "derivative-at",
    topic: "calculus",
    difficulty: "hard",
    year: "12",
    source: "bank",
    instructionId: "findDerivative",
    promptTex: "f(x) = x^3 - 6x,\\; f'(2) = ?",
    solutionTex: "f'(2) = 6",
    graphExpr: "x^3 - 6x",
  },
  {
    id: "bank-vec-01",
    templateId: "vector-magnitude",
    topic: "vectors",
    difficulty: "easy",
    year: "9",
    source: "bank",
    instructionId: "evaluate",
    promptTex: "\\lVert (3, 4) \\rVert = ?",
    solutionTex: "5",
    formula: "hypot(a, b)",
    variables: { a: 3, b: 4 },
    promptTemplate: "\\lVert ({{a}}, {{b}}) \\rVert = ?",
  },
  {
    id: "bank-vec-02",
    templateId: "vector-dot",
    topic: "vectors",
    difficulty: "medium",
    year: "10",
    source: "bank",
    instructionId: "evaluate",
    promptTex:
      "\\vec{a} = (2, -1),\\; \\vec{b} = (3, 4),\\; \\vec{a}\\cdot\\vec{b} = ?",
    solutionTex: "2",
    formula: "ax * bx + ay * by",
    variables: { ax: 2, ay: -1, bx: 3, by: 4 },
    promptTemplate:
      "\\vec{a} = ({{ax}}, {{ay}}),\\; \\vec{b} = ({{bx}}, {{by}}),\\; \\vec{a}\\cdot\\vec{b} = ?",
  },
];
